project:
  type: website
  output-dir: docs
  render:
    - 1_1.qmd
    - 1_1b.qmd
    - 1_2.qmd
    - week1_3.qmd
    - week1_4.qmd
    - week2_1.qmd
    - week2_2.qmd
    - week2_3.qmd
    - week2_4.qmd
    - week2_5a.qmd
    - week2_5b.qmd
    - week2_5c.qmd
    - week2_5d.qmd
    - week2_5e.qmd
    - week2_5f.qmd
    - week2_5g.qmd
    - week3_1.qmd
    - week3_2.qmd
    - week3_3.qmd
    - week3_4.qmd
website:
  title: "PSYC559: Applied Machine Learning in Psychology"
  sidebar:
    style: "docked"
    search: false
    contents:
      - text: "Table of Contents"
        href: introduction.qmd
        contents: 
      - section: "Introduction to R"
        contents:
          - 1_1.qmd
          - 1_1b.qmd
          - 1_2.qmd
          - week1_3.qmd
          - week1_4.qmd
      - section: "Introduction to Machine Learning"
        contents:
          - week2_1.qmd
          - week2_2.qmd
          - week2_3.qmd
          - week2_4.qmd
      - section: "Feature Engineering"
        contents:    
          - week2_5a.qmd
          - week2_5b.qmd
          - week2_5c.qmd
          - week2_5d.qmd
          - week2_5e.qmd
          - week2_5f.qmd
          - week2_5g.qmd
      - section: "Regression"
        contents:    
          - week3_1.qmd
          - week3_2.qmd
          - week3_3.qmd
          - week3_4.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual


