project:
  type: website
  output-dir: docs
website:
  title: "PSYC559: Applied Machine Learning"
  sidebar:
    style: "docked"
    search: false
    contents:
      - text: "Introduction"
        href: introduction.qmd
        contents: 
      - section: "Week 1: Fundamentals"
        contents:
          - week1_1.qmd
      - section: "Week 2: Centrality"
        contents:
          - week2_1.qmd
          - week2_2.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual


