project:
  type: website
  output-dir: docs
website:
  title: "PSYC559: Applied Machine Learning in Psychology"
  sidebar:
    style: "docked"
    search: false
    contents:
      - text: "Table of Contents"
        href: introduction.qmd
        contents: 
      - section: "Introduction to R"
        contents:
          - week1_1.qmd
          - week1_1b.qmd
          - week1_2.qmd
          - week1_3.qmd
          - week1_4.qmd
      - section: "Introduction to Machine Learning"
        contents:
          - week2_1.qmd
          - week2_2.qmd
          - week2_3.qmd
          - week2_4.qmd
          - week2_5.qmd
          #- week2_2b.qmd
     # - section: "Assignments"
     #   contents:
     #     - assignment1_1.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual


