---
title: "Introduction to Network Analysis"
author: "Jonathan J. Park"
---

Welcome to the first week of Network Analysis to both the PSC-190 and PSC-290 students.

To start off the quarter, we will review the syllabus which--much like this website--contains the list of topics we will try to cover throughout the quarter. Likewise, it contains a breakdown of your quarter grades, class policies, and information regarding your presentations and quarter projects.

## The Syllabus

[Students may review the syllabus on Canvas](https://canvas.ucdavis.edu/).
We will discuss the uniquenesses of both courses and the connections between the two in a later section.

## Final Project

Throughout the quarter, students will be introduced to a myriad of analytic methods in graph theory and network analysis. Often, the ultimate goal of these course formats is to generate some research report that may--eventually--be ready for publication.

In my own experience, these very rarely pan out due to how quickly a quarter unfolds over time. Instead of a full scale research project, your goal for this quarter is to design a project proposal.

This includes but is not limited to:

1.  An introduction section to the topic [if focusing on a substantive question] and the analytic technique
2.  A methods section introducing the analytic technique in detail. This should include:
    -   The analytic form of the technique
    -   The strengths and limitations of this method
3.  An analytic plan describing:
    -   Why this technique was chosen over alternative avenues
    -   The expected results and how it will be applied
    -   A skeleton code for running the analysis
    -   [Optional] Either a simulated showcase or an application to real-data to demonstrate the potential results

## Class Presentation

Students will be in-charge for presenting on one of the topics during the quarter.
If there are more students than there are topics, you are welcome to form teams to present.

Once topics are assigned, it will be your job to prepare the `.qmd` file for the week you have been assigned.

In your `.qmd`, you will provide an outline of the research articles that were assigned for the week as well as implementation of the technique to code. In the week prior to your presentation, you will be required to meet with me to discuss your plans for the presentation.

In our meeting, we will review your plans and discuss places where more detail could be added. Likewise, for your coding example, we will work together to generate a set of code that will clearly illustrate the method using examples relevant to your interests.

Finally, student presenters will generate the weekly reflection questions and coding challenges for their week.

## Class Format

The general layout of each weekly meeting is as follows:

1.  A topical overview of the readings for the current week and discussion
    1.  These will be led by the student presenters that week with the goal of facilitating discussion 
    2.  Discussions may include comments or questions resulting from the readings or other, ideas inspired by the readings
    3.  Students are encouraged to bring their own lived experiences, interests, and knowledge to these conversations. Participation is a major component of this course and we will be meeting for $\sim 3$ hours each week.
2.  A translation of the readings of the week into actionable code
    1.  These will be led by the student presenters of the week
    2.  Code will be reviewed by me--the instructor--prior to presentation to make sure it is thorough and free of bugs
    3.  Students will be in charge of developing a problem set for the week consisting of strengths, limitations, and application of the methods


# Getting sta$\texttt{R}$ted with $\texttt{R}$

If you have not done so already, you will need to download [R](https://ftp.osuosl.org/pub/cran/) and [RStudio](https://posit.co/download/rstudio-desktop/).

$\texttt{R}$ is a programming language that is popular among researchers in statistics, econometrics, and the social and behavioral sciences. It has a great deal of utility for modeling and visualizing data and will be our primary tool for testing concepts in this seminar.

**If you have never used $\texttt{R}$ or have never coded in your entire life, that is fine**!

You will be walked through basic $\texttt{R}$ coding and functions when they are introduced. Even in instances where you are presenting and developing the coding sets for the coming week, you will be guided by myself with coding suggestions and support. Fear of coding is not a reason to be worried about your success in this course!

For those who have little to no experience in $\texttt{R}$, I recommend reviewing these tutorials I put together for PSC-012Y:

-   [Video Tutorials for R, RStudio, and .RMD](https://video.ucdavis.edu/playlist/dedicated/1_9f4qti0u/1_gohted0b)

If you would like to follow along with the coding tutorial you can download these files to practice:

-   [Example `.RMD` file](https://www.dropbox.com/scl/fi/4ns59amo2nip82p1epkbu/01_VirtualTutorial_Student_Ver.Rmd?rlkey=5w5nt12qpxule3znwmq4lo01f&dl=0)
-   [`.PDF` to Follow Along](https://www.dropbox.com/scl/fi/x1jlelkqt9lrda00h6egy/01_Week_PSC_012Y.pdf?rlkey=05k45h2p019mudl12iuc5cfa7&dl=0)
-   [Example Dataset](https://www.dropbox.com/scl/fi/1y99u7njy79tpnd4nimsv/OL1.dat?rlkey=ky998pd7djs39071h4iojqbed&dl=0)

You will find that the video tutorials cover a format called "`.RMD`" which differs from the "`.qmd`" files you will be working with in this course. There is very little--if any--difference between the two formats for the purposes of this class. 












